In [5]:
import pandas as pd
import numpy as np
import networkx as nx
import pickle
import matplotlib.pyplot as plt

from sklearn.cluster import HDBSCAN
from sklearn.preprocessing import StandardScaler

from analysis_02_class import calculate_vector_stats, save_plot_graph_with_labels

In [6]:
main_df = pd.read_csv(f"small_data/main_df.csv")

In [7]:
main_df

,Exp_ID,Image_Metadata_Site,track_id,Image_Metadata_T,Nuclear_size,ERKKTR_ratio,FoxO3A_ratio,objNuclei_Location_Center_X,objNuclei_Location_Center_Y
0,1,1,1,0,303.000,0.704407,1.33383,932.211,875.248
1,1,1,1,1,333.000,0.848242,1.33791,932.150,874.174
2,1,1,1,2,314.000,1.059170,1.37627,932.376,873.787
3,1,1,1,3,322.000,1.188000,1.35754,932.168,873.453
4,1,1,1,4,313.999,1.205540,1.36695,931.146,872.885
...,...,...,...,...,...,...,...,...,...
356627,1,1,2857,253,165.000,0.597341,1.32403,1019.050,771.624
356628,1,1,2857,254,192.000,0.587024,1.28853,1019.060,773.099
356629,1,1,2857,255,200.000,0.587822,1.28325,1019.100,773.540
356630,1,1,2857,256,192.000,0.579069,1.29542,1018.930,772.469
356631,1,1,2857,257,175.000,0.589269,1.31594,1018.850,771.611

In [8]:
sorted_main_df = main_df.set_index(['Image_Metadata_T', 'track_id']).sort_index()
sorted_main_df

                           Exp_ID  Image_Metadata_Site  Nuclear_size  \
Image_Metadata_T track_id
0                1              1                    1       303.000
                 2              1                    1       268.001
                 3              1                    1       370.000
                 4              1                    1       341.000
                 5              1                    1       308.000
...                           ...                  ...           ...
257              2849           1                    1       165.000
                 2850           1                    1       138.000
                 2855           1                    1       148.000
                 2856           1                    1       148.000
                 2857           1                    1       175.000

                           ERKKTR_ratio  FoxO3A_ratio  \
Image_Metadata_T track_id
0                1             0.704407       1.33383
                 2             1.227760       1.20592
                 3             0.779226       1.27561
                 4             0.870780       1.34460
                 5             0.807262       1.47321
...                                 ...           ...
257              2849          0.607956       1.31242
                 2850          0.775133       1.15722
                 2855          1.114600       1.25315
                 2856          0.861735       1.16059
                 2857          0.589269       1.31594

                           objNuclei_Location_Center_X  \
Image_Metadata_T track_id
0                1                             932.211
                 2                             162.328
                 3                             647.816
                 4                             642.988
                 5                             990.718
...                                                ...
257              2849                          839.988
                 2850                         1019.510
                 2855                          411.797
                 2856                         1018.580
                 2857                         1018.850

                           objNuclei_Location_Center_Y
Image_Metadata_T track_id
0                1                            875.2480
                 2                            365.4140
                 3                            846.5760
                 4                            827.8650
                 5                             59.4675
...                                                ...
257              2849                         877.9760
                 2850                          50.1159
                 2855                         205.4320
                 2856                         809.4530
                 2857                         771.6110

[356632 rows x 7 columns]

In [9]:
def read_graph(path: str) -> nx.Graph:
    with open(path, "rb") as file:
        loaded_data = pickle.load(file)

    return loaded_data

In [10]:
graphs: dict[int, nx.Graph] = {}

for time_t in sorted_main_df.index.get_level_values(0).unique():
    graphs[time_t] = read_graph(f"big_data/E1S1/graph_pickles/t_{time_t}.pkl")

In [11]:
stats_vectors_dict: dict[int, dict[int, np.ndarray]] = {}

for time_t in range(len(graphs.keys())-1):
    stats_vectors_dict[time_t] = calculate_vector_stats(graphs[time_t], graphs[time_t+1])

    print(f"{time_t}. Done!")

0. Done!
1. Done!
2. Done!
3. Done!
4. Done!
5. Done!
6. Done!
7. Done!
8. Done!
9. Done!
10. Done!
11. Done!
12. Done!
13. Done!
14. Done!
15. Done!
16. Done!
17. Done!
18. Done!
19. Done!
20. Done!
21. Done!
22. Done!
23. Done!
24. Done!
25. Done!
26. Done!
27. Done!
28. Done!
29. Done!
30. Done!
31. Done!
32. Done!
33. Done!
34. Done!
35. Done!
36. Done!
37. Done!
38. Done!
39. Done!
40. Done!
41. Done!
42. Done!
43. Done!
44. Done!
45. Done!
46. Done!
47. Done!
48. Done!
49. Done!
50. Done!
51. Done!
52. Done!
53. Done!
54. Done!
55. Done!
56. Done!
57. Done!
58. Done!
59. Done!
60. Done!
61. Done!
62. Done!
63. Done!
64. Done!
65. Done!
66. Done!
67. Done!
68. Done!
69. Done!
70. Done!
71. Done!
72. Done!
73. Done!
74. Done!
75. Done!
76. Done!
77. Done!
78. Done!
79. Done!
80. Done!
81. Done!
82. Done!
83. Done!
84. Done!
85. Done!
86. Done!
87. Done!
88. Done!
89. Done!
90. Done!
91. Done!
92. Done!
93. Done!
94. Done!
95. Done!
96. Done!
97. Done!
98. Done!
99. Done!
100. Done!
101. Done!
102. Done!
103. Done!
104. Done!
105. Done!
106. Done!
107. Done!
108. Done!
109. Done!
110. Done!
111. Done!
112. Done!
113. Done!
114. Done!
115. Done!
116. Done!
117. Done!
118. Done!
119. Done!
120. Done!
121. Done!
122. Done!
123. Done!
124. Done!
125. Done!
126. Done!
127. Done!
128. Done!
129. Done!
130. Done!
131. Done!
132. Done!
133. Done!
134. Done!
135. Done!
136. Done!
137. Done!
138. Done!
139. Done!
140. Done!
141. Done!
142. Done!
143. Done!
144. Done!
145. Done!
146. Done!
147. Done!
148. Done!
149. Done!
150. Done!
151. Done!
152. Done!
153. Done!
154. Done!
155. Done!
156. Done!
157. Done!
158. Done!
159. Done!
160. Done!
161. Done!
162. Done!
163. Done!
164. Done!
165. Done!
166. Done!
167. Done!
168. Done!
169. Done!
170. Done!
171. Done!
172. Done!
173. Done!
174. Done!
175. Done!
176. Done!
177. Done!
178. Done!
179. Done!
180. Done!
181. Done!
182. Done!
183. Done!
184. Done!
185. Done!
186. Done!
187. Done!
188. Done!
189. Done!
190. Done!
191. Done!
192. Done!
193. Done!
194. Done!
195. Done!
196. Done!
197. Done!
198. Done!
199. Done!
200. Done!
201. Done!
202. Done!
203. Done!
204. Done!
205. Done!
206. Done!
207. Done!
208. Done!
209. Done!
210. Done!
211. Done!
212. Done!
213. Done!
214. Done!
215. Done!
216. Done!
217. Done!
218. Done!
219. Done!
220. Done!
221. Done!
222. Done!
223. Done!
224. Done!
225. Done!
226. Done!
227. Done!
228. Done!
229. Done!
230. Done!
231. Done!
232. Done!
233. Done!
234. Done!
235. Done!
236. Done!
237. Done!
238. Done!
239. Done!
240. Done!
241. Done!
242. Done!
243. Done!
244. Done!
245. Done!
246. Done!
247. Done!
248. Done!
249. Done!
250. Done!
251. Done!
252. Done!
253. Done!
254. Done!
255. Done!
256. Done!

In [12]:
time_dfs: dict[int, pd.DataFrame] = {}
for time_t in range(len(graphs.keys())-1):
    time_dfs[time_t] = pd.DataFrame(stats_vectors_dict[time_t]).transpose()

    time_dfs[time_t]["Image_Metadata_T"] = [time_t for _ in range(len(time_dfs[time_t]))]

    time_dfs[time_t]['track_id'] = time_dfs[time_t].index

    time_dfs[time_t] = time_dfs[time_t].set_index(['Image_Metadata_T', 'track_id'])

In [13]:
E1S1_data_frame: pd.DataFrame = pd.concat([df for df in time_dfs.values()])

In [14]:
E1S1_data_frame.sort_index()

                             0        1         2        3           4  \
Image_Metadata_T track_id
0                1         1.0  303.000  0.704407  1.33383  291.166833
                 2         1.0  268.001  1.227760  1.20592  391.571286
                 3         1.0  370.000  0.779226  1.27561  294.333500
                 4         1.0  341.000  0.870780  1.34460  326.333333
                 5         1.0  308.000  0.807262  1.47321  239.800000
...                        ...      ...       ...      ...         ...
256              2849      1.0  155.000  0.602840  1.27858  297.750000
                 2850      1.0  144.000  0.770935  1.15876  320.249500
                 2855      1.0  152.000  1.167480  1.29487  372.250250
                 2856      1.0  146.000  0.852457  1.14507  285.000000
                 2857      1.0  192.000  0.579069  1.29542  213.000250

                                   5         6         7         8         9  \
Image_Metadata_T track_id
0                1         50.031588  1.066516  0.162704  1.332942  0.174318
                 2         69.035537  0.911929  0.369445  1.302593  0.102663
                 3         57.519960  0.771776  0.229322  1.189287  0.272200
                 4         82.639030  0.844307  0.187100  1.350673  0.114783
                 5         77.685005  0.880344  0.205471  1.166042  0.152828
...                              ...       ...       ...       ...       ...
256              2849      36.002937  0.763065  0.141762  1.288737  0.113180
                 2850      42.257180  0.902870  0.184382  1.238428  0.049756
                 2855      46.045536  0.932223  0.286751  1.448847  0.131609
                 2856      99.502094  0.997636  0.291094  1.271313  0.034103
                 2857      55.995803  0.967797  0.202919  1.285238  0.086835

                            10
Image_Metadata_T track_id
0                1         6.0
                 2         7.0
                 3         6.0
                 4         6.0
                 5         5.0
...                        ...
256              2849      4.0
                 2850      4.0
                 2855      4.0
                 2856      3.0
                 2857      4.0

[355295 rows x 11 columns]

# Data Science

In [15]:
st_scaler_1_6 = StandardScaler().fit(E1S1_data_frame[[1, 2, 3]])

normalized_data_1_6 = StandardScaler().fit_transform(E1S1_data_frame[[1, 2, 3, 4, 5, 6]])

normalized_data_7_9 = StandardScaler().fit_transform(E1S1_data_frame[[7, 8, 9]])

normalized_data_10 = StandardScaler().fit_transform(E1S1_data_frame[[10]])

In [16]:
normalized_data = np.hstack([E1S1_data_frame[[0]].astype(np.int32).to_numpy(), normalized_data_1_6, normalized_data_7_9, normalized_data_10])

normalized_data

array([[ 1.        ,  0.07243322,  0.88578957, ...,  0.30335443,
        -1.02695043, -2.57105387],
       [ 1.        , -0.782241  , -0.23190641, ...,  0.31955896,
        -1.14677713, -1.65441898],
       [ 1.        ,  0.87087886, -0.30425393, ...,  2.34331935,
         0.48535488, -0.73778409],
       ...,
       [ 1.        , -0.42237817,  0.91673931, ..., -0.91043677,
        -1.58667329,  1.0954857 ],
       [ 1.        , -0.42237817, -0.54046602, ..., -0.15220522,
        -1.44517048,  0.17885081],
       [ 1.        , -0.04002392,  0.54060141, ..., -0.48637617,
        -0.59422901,  0.17885081]], shape=(355295, 11))

In [17]:
labels = HDBSCAN(min_cluster_size=256).fit_predict(normalized_data)

E1S1_data_frame["label"] = labels

/home/kchadzynski/Pulpit/python/Voronoi_graph_in_time/venv/lib64/python3.14/site-packages/sklearn/cluster/_hdbscan/hdbscan.py:722: FutureWarning: The default value of `copy` will change from False to True in 1.10. Explicitly set a value for `copy` to silence this warning.
  warn(

In [18]:
E1S1_data_frame

                             0        1         2        3           4  \
Image_Metadata_T track_id
0                1201      1.0  333.000  1.067420  1.44699  339.333333
                 1495      1.0  257.000  0.789709  1.37906  400.749500
                 874       1.0  404.000  0.771733  1.41822  294.999600
                 304       1.0  336.999  0.646938  1.23549  342.000000
                 211       1.0  502.000  0.503123  1.08330  321.999500
...                        ...      ...       ...      ...         ...
256              446       1.0  351.000  1.190230  1.25376  281.666333
                 1615      1.0  275.000  1.076400  1.41562  378.714000
                 712       1.0  289.000  1.075110  1.11577  317.428714
                 798       1.0  289.000  0.713042  1.39155  365.833667
                 749       1.0  323.000  0.981652  1.26309  279.166833

                                    5         6         7         8         9  \
Image_Metadata_T track_id
0                1201       59.015661  0.740077  0.059859  1.330717  0.064827
                 1495      121.970313  0.747548  0.164359  1.331925  0.057100
                 874        85.421140  1.009750  0.366792  1.482832  0.162352
                 304        46.654550  0.954368  0.350935  1.428672  0.114526
                 211        35.163696  0.781324  0.050461  1.267478  0.089554
...                               ...       ...       ...       ...       ...
256              446        47.397838  0.777955  0.091818  1.233957  0.087437
                 1615       76.596976  0.822990  0.207533  1.307099  0.117374
                 712        83.848683  0.745183  0.132189  1.240207  0.028732
                 798        29.480717  0.849192  0.163996  1.296747  0.037857
                 749        41.610942  0.803160  0.154715  1.271828  0.092732

                            10  label
Image_Metadata_T track_id
0                1201      3.0     -1
                 1495      4.0     -1
                 874       5.0     -1
                 304       6.0     -1
                 211       4.0     -1
...                        ...    ...
256              446       6.0     -1
                 1615      7.0     -1
                 712       7.0     -1
                 798       6.0     -1
                 749       6.0     -1

[355295 rows x 12 columns]

In [19]:
E1S1_data_frame["label"].unique()

array([-1,  0,  1])

In [20]:
sum(E1S1_data_frame["label"] == 1)

277

In [ ]:
time_t = 0

id_to_idx_dict: dict[int, int] = {val: key for val, key in nx.get_node_attributes(graphs[time_t], "cell_id").items()}
for lab_idx in graphs[time_t].nodes:
    print(E1S1_data_frame.loc[(time_t, id_to_idx_dict[lab_idx])]["label"])

-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0

In [27]:
for time_t in E1S1_data_frame.index.get_level_values(0).unique():

    save_plot_graph_with_labels(
        graphs[time_t],
        E1S1_data_frame.loc[time_t]["label"].to_numpy(),
        f"big_data/E1S1/graph_pics_clustered/t_{time_t}.png"
    )

    print(f"{time_t}. Done!")

0. Done!
1. Done!
2. Done!
3. Done!
4. Done!
5. Done!
6. Done!
7. Done!
8. Done!
9. Done!
10. Done!
11. Done!
12. Done!
13. Done!
14. Done!
15. Done!
16. Done!
17. Done!
18. Done!
19. Done!
20. Done!
21. Done!
22. Done!
23. Done!
24. Done!
25. Done!
26. Done!
27. Done!
28. Done!
29. Done!
30. Done!
31. Done!
32. Done!
33. Done!
34. Done!
35. Done!
36. Done!
37. Done!
38. Done!
39. Done!
40. Done!
41. Done!
42. Done!
43. Done!
44. Done!
45. Done!
46. Done!
47. Done!
48. Done!
49. Done!
50. Done!
51. Done!
52. Done!
53. Done!
54. Done!
55. Done!
56. Done!
57. Done!
58. Done!
59. Done!
60. Done!
61. Done!
62. Done!
63. Done!
64. Done!
65. Done!
66. Done!
67. Done!
68. Done!
69. Done!
70. Done!
71. Done!
72. Done!
73. Done!
74. Done!
75. Done!
76. Done!
77. Done!
78. Done!
79. Done!
80. Done!
81. Done!
82. Done!
83. Done!
84. Done!
85. Done!
86. Done!
87. Done!
88. Done!
89. Done!
90. Done!
91. Done!
92. Done!
93. Done!
94. Done!
95. Done!
96. Done!
97. Done!
98. Done!
99. Done!
100. Done!
101. Done!
102. Done!
103. Done!
104. Done!
105. Done!
106. Done!
107. Done!
108. Done!
109. Done!
110. Done!
111. Done!
112. Done!
113. Done!
114. Done!
115. Done!
116. Done!
117. Done!
118. Done!
119. Done!
120. Done!
121. Done!
122. Done!
123. Done!
124. Done!
125. Done!
126. Done!
127. Done!
128. Done!
129. Done!
130. Done!
131. Done!
132. Done!
133. Done!
134. Done!
135. Done!
136. Done!
137. Done!
138. Done!
139. Done!
140. Done!
141. Done!
142. Done!
143. Done!
144. Done!
145. Done!
146. Done!
147. Done!
148. Done!
149. Done!
150. Done!
151. Done!
152. Done!
153. Done!
154. Done!
155. Done!
156. Done!
157. Done!
158. Done!
159. Done!
160. Done!
161. Done!
162. Done!
163. Done!
164. Done!
165. Done!
166. Done!
167. Done!
168. Done!
169. Done!
170. Done!
171. Done!
172. Done!
173. Done!
174. Done!
175. Done!
176. Done!
177. Done!
178. Done!
179. Done!
180. Done!
181. Done!
182. Done!
183. Done!
184. Done!
185. Done!
186. Done!
187. Done!
188. Done!
189. Done!
190. Done!
191. Done!
192. Done!
193. Done!
194. Done!
195. Done!
196. Done!
197. Done!
198. Done!
199. Done!
200. Done!
201. Done!
202. Done!
203. Done!
204. Done!
205. Done!
206. Done!
207. Done!
208. Done!
209. Done!
210. Done!
211. Done!
212. Done!
213. Done!
214. Done!
215. Done!
216. Done!
217. Done!
218. Done!
219. Done!
220. Done!
221. Done!
222. Done!
223. Done!
224. Done!
225. Done!
226. Done!
227. Done!
228. Done!
229. Done!
230. Done!
231. Done!
232. Done!
233. Done!
234. Done!
235. Done!
236. Done!
237. Done!
238. Done!
239. Done!
240. Done!
241. Done!
242. Done!
243. Done!
244. Done!
245. Done!
246. Done!
247. Done!
248. Done!
249. Done!
250. Done!
251. Done!
252. Done!
253. Done!
254. Done!
255. Done!
256. Done!

# GIF making

In [28]:
import imageio.v3 as imageio

In [30]:
ims = [imageio.imread(f"big_data/E1S1/graph_pics_clustered/t_{time_idx}.png") for time_idx in E1S1_data_frame.index.get_level_values(0).unique()]

imageio.imwrite("big_data/E1S1/graphs_clustered.gif", ims, fps = 60)