In [ ]:
import pandas as pd
import numpy as np
import imageio.v3 as imageio

from analysis_01_class import MakeGraphFromSingleTime

In [3]:
main_df = pd.read_csv(f"small_data/main_df.csv")

In [4]:
main_df

,Exp_ID,Image_Metadata_Site,track_id,Image_Metadata_T,Nuclear_size,ERKKTR_ratio,FoxO3A_ratio,objNuclei_Location_Center_X,objNuclei_Location_Center_Y
0,1,1,1,0,303.000,0.704407,1.33383,932.211,875.248
1,1,1,1,1,333.000,0.848242,1.33791,932.150,874.174
2,1,1,1,2,314.000,1.059170,1.37627,932.376,873.787
3,1,1,1,3,322.000,1.188000,1.35754,932.168,873.453
4,1,1,1,4,313.999,1.205540,1.36695,931.146,872.885
...,...,...,...,...,...,...,...,...,...
356627,1,1,2857,253,165.000,0.597341,1.32403,1019.050,771.624
356628,1,1,2857,254,192.000,0.587024,1.28853,1019.060,773.099
356629,1,1,2857,255,200.000,0.587822,1.28325,1019.100,773.540
356630,1,1,2857,256,192.000,0.579069,1.29542,1018.930,772.469
356631,1,1,2857,257,175.000,0.589269,1.31594,1018.850,771.611

In [5]:
sorted_main_df = main_df.set_index(['Image_Metadata_T', 'track_id']).sort_index()
sorted_main_df

                           Exp_ID  Image_Metadata_Site  Nuclear_size  \
Image_Metadata_T track_id
0                1              1                    1       303.000
                 2              1                    1       268.001
                 3              1                    1       370.000
                 4              1                    1       341.000
                 5              1                    1       308.000
...                           ...                  ...           ...
257              2849           1                    1       165.000
                 2850           1                    1       138.000
                 2855           1                    1       148.000
                 2856           1                    1       148.000
                 2857           1                    1       175.000

                           ERKKTR_ratio  FoxO3A_ratio  \
Image_Metadata_T track_id
0                1             0.704407       1.33383
                 2             1.227760       1.20592
                 3             0.779226       1.27561
                 4             0.870780       1.34460
                 5             0.807262       1.47321
...                                 ...           ...
257              2849          0.607956       1.31242
                 2850          0.775133       1.15722
                 2855          1.114600       1.25315
                 2856          0.861735       1.16059
                 2857          0.589269       1.31594

                           objNuclei_Location_Center_X  \
Image_Metadata_T track_id
0                1                             932.211
                 2                             162.328
                 3                             647.816
                 4                             642.988
                 5                             990.718
...                                                ...
257              2849                          839.988
                 2850                         1019.510
                 2855                          411.797
                 2856                         1018.580
                 2857                         1018.850

                           objNuclei_Location_Center_Y
Image_Metadata_T track_id
0                1                            875.2480
                 2                            365.4140
                 3                            846.5760
                 4                            827.8650
                 5                             59.4675
...                                                ...
257              2849                         877.9760
                 2850                          50.1159
                 2855                         205.4320
                 2856                         809.4530
                 2857                         771.6110

[356632 rows x 7 columns]

In [6]:
make_graph: MakeGraphFromSingleTime

for time_idx in sorted_main_df.index.get_level_values('Image_Metadata_T').unique():
    make_graph = MakeGraphFromSingleTime(sorted_main_df.loc[time_idx])
    make_graph.save_graph_pic(f"big_data/E1S1/graph_pics/t_{time_idx}.png")

In [10]:
ims = [imageio.imread(f"big_data/E1S1/graph_pics/t_{time_idx}.png") for time_idx in sorted_main_df.index.get_level_values('Image_Metadata_T').unique()]

imageio.imwrite("big_data/E1S1/graphs.gif", ims, fps = 60)

In [11]:
make_graph: MakeGraphFromSingleTime

for time_idx in sorted_main_df.index.get_level_values('Image_Metadata_T').unique():
    make_graph = MakeGraphFromSingleTime(sorted_main_df.loc[time_idx])
    make_graph.save_graph(f"big_data/E1S1/graph_pickles/t_{time_idx}.pkl")